deps: use go1.17 and remove GO111MODULE
Shopify/kubeaudit pull request #382
Opened 2021-11-20 18:22 UTC by chenrui333

- deps: update to use go1.17
- remove `GO111MODULE` setting as go1.16 defaults to go mod build

2021-11-20 18:23 UTC, chenrui333 commented
signed the CLA.

2021-11-29 15:23 UTC, dani-santos-code approved these changes
hi, @chenrui333 ! Thank you for your contribution. It looks good!

2021-11-30 14:53 UTC, dani-santos-code commented
can we merge this @genevieveluyt ?

2021-11-30 15:27 UTC, genevieveluyt requested changes

2021-11-30 15:27 UTC, genevieveluyt commented on go.mod
> +require (
Are there supposed to be two `require` blocks? Can you please run `go mod tidy`?

2021-11-30 15:55 UTC, genevieveluyt commented on go.mod
> +require (
Interesting, thanks for context!

2021-11-30 16:00 UTC, genevieveluyt commented
@chenrui333 there are a couple other places that still reference 1.16 if you wouldn't mind updating those as well

- [ ] https://github.com/Shopify/kubeaudit/blob/main/goreleaser.Dockerfile#L1
- [ ] https://github.com/Shopify/kubeaudit/blob/main/Dockerfile#L1
- [ ] https://github.com/Shopify/kubeaudit/blob/main/Makefile#L13
- [ ] https://github.com/Shopify/kubeaudit/blob/main/README.md?plain=1#L50

2022-03-11 21:25 UTC, closed without merging